### PR TITLE
Add patch ability to update paypal order

### PR DESCRIPTION
**Pull request by jtapia**
Based on https://github.com/paypal/Checkout-Ruby-SDK/blob/685b0637404f3f38cfb5234d294293c294f175de/lib/orders/orders_patch_request.rb we are able to use `PATCH` to update Paypal Order information

### CODE REVIEW

**Comment by kennyadsl** [comment]
Thanks! Can you please describe the flow that requires this new endpoint?

**Comment by jakemumu** [comment]
@kennyadsl  -- on our site, we use a single page checkout with PayPal. Because we don't have address at the time of checkout, and we have the delivery step removed from checkout, we found this messed the flow up quite a bit. 

The solution was to manually force an update on the order after we receive back the address and can update tax accordingly. At least that was my understanding of the problem @jtapia created the solution. 

In general it was helpful to be able to patch the order how we needed based on a customized checkout flow. The gem seems to skip tax calculations with the delivery step removed.

**Comment by kennyadsl** [comment]
@jtapia @jakemumu thanks, that makes sense. Is there any way to add some tests for this new endpoint and behavior?

**Comment by elia** [comment]
@jtapia @jakemumu I'm closing this, the new approach is to always install frontend related stuff in the target application with the generator instead of providing them through the engine and then resort to monkey patching. We're about to release one last version supporting solidus_frontend and then we'll switch to the new mode and only support solidus_starter_frontend.

**Pull request closed without merging**
