### PR TITLE
Truncate the product name to 127 characters

### LINKED ISSUE #135: Invalid string length error
Looks like PayPal has max string length validations, and when a product's title is too long, a 422 is returned. 

This happens when clicking one of the PayPal buttons on the cart or product page. 

Here are the console errors: 

Screen Shot 2021-11-09 at 8 05 17 PM

and digging a bit deeper, PayPal returns: 

`{"table":{"status_code":422,"error":{"table":{"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"4365e6b61e3e","details":[{"table":{"field":"/purchase_units/@reference_id=='default'/items/0/name","value":"Guayaki Yerba Mate, Cranberry Pomegranate, Organic Sparkling Alternative to Soda, Tea, and Energy Drinks, 12 Ounce Cans (Pack of 12), 80mg Caffeine","location":"body","issue":"INVALID_STRING_LENGTH","description":"The value of a field is either too short or too long."},"modifiable":true}],"links":[{"table":{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH","rel":"information_link","encType":"application/json"},"modifiable":true}]},"modifiable":true}}}`

In this case, the product's title is: 

Guayaki Yerba Mate, Cranberry Pomegranate, Organic Sparkling Alternative to Soda, Tea, and Energy Drinks, 12 Ounce Cans (Pack of 12), 80mg Caffeine

### PR DESCRIPTION
**Pull request by DanielePalombo**
fix #135

### CODE REVIEW

**Comment by DanielePalombo** [comment]
@RyanofWoods can you put an eye on it?

**Comment by RyanofWoods** [comment]
> @RyanofWoods can you put an eye on it?

What do you mean @DanielePalombo ?

**Comment by DanielePalombo** [comment]
@RyanofWoods can you review the PR?

**Review by elia — APPROVED** [review]

**Review by elia — APPROVED** [review]
Thanks, rebased and approved ✅

**Comment by elia** [comment]
_Created https://github.com/solidusio/circleci-orbs-extensions/pull/62 to address the issue in the circleci ORB_

**Pull request merged**
